name: Update User Guide

on:
  push:
    paths:
      - 'userguide/**'
      - '.github/workflows/update-userguide.yml'

jobs:
  update-userguide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Setup sdkman and install znai
        id:  installznai
        uses: sdkman/sdkman-action@master
        with:
          candidate: znai
          version: 1.69
      - name: Build and Deploy User Guide
        run: |
          unzip -d /tmp/znai ${{ steps.installznai.outputs.file }}
          ls -ltR /tmp/znai
          cd userguide
          /tmp/znai/dist/znai --doc-id groovy-ngs-utils/userguide --deploy ./deploy
      - name: Commit and Push Updates
        env:
           PAT: ${{ secrets.PAGES_DEPLOY_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git clone https://github.com/ssadedin/ssadedin.github.io.git deploy_repo
          cp -r userguide/deploy/* deploy_repo/groovy-ngs-utils/userguide/
          cd deploy_repo
          git add .
          git commit -m 'Update user guide for groovy-ngs' || echo "No changes to commit"
          git push
